language: node_js
node_js: 8
sudo: required
git:
  depth: 5
branches:
  only:
  - "/^(?i:SWIK)-.*$/"
  - master
cache:
  directories:
  - "./application/node_modules"
before_install:
- if [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST" = "false" ] ; then ./travis_scripts/install_compose.sh ; fi
- cd application
before_script:
- npm update --dev
- npm run start:mongodb
script:
- sleep 15
- npm run lint
- npm run test:unit
- npm run test:integration
after_success:
- cd ..
- openssl aes-256-cbc -K $encrypted_129f69af3727_key -iv $encrypted_129f69af3727_iv -in deployment_keys.tar.enc -out deployment_keys.tar -d
- if [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST" = "false" ] ; then ./travis_scripts/dockerhub.sh ; fi
- if [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST" = "false" ] ; then ./travis_scripts/deploy.sh ; fi
- cd application
after_script:
- npm run coverall
- npm run stop:mongodb
- rm -f deployment_keys.tar
- rm -f ~/.docker/{cert.pem,key.pem,ca.pem,config.json}
services:
- docker
notifications:
  slack:
    on_success: change
    on_failure: always
    rooms:
      secure: sjC9Jp7A/2DtxvlhsFcmHpuQK7LBXEvHj2SiBw1m3IMi726AYrj2OtLvbX3aqsA7f3nux/YEdr4gA1zhrLYnWCLWcOpQUo9VhcRppxTqIw/PqoCwbsVemWqGqZSeng7gZFhNuD2437LA6KvhJ3jPkiDJykcLpofqck9jAdb51JOdX0eU2qne0Ecqz/WRplzR/88Eh6FelIjnVb94ZKgh4MLqaDF1t2M3Gy/VTd9KhcyB37wiS9XZU6WCsPGVTR/ivGrFTr3yWzn0hj2CwzYKB+/gyMx+yLJKBc3KeiRZXhVm0GgI88yfYze8sX0Dz5/RATzFo+5D2vrn4L+tQ/WgenC7qHImKpnjTZHnfbuRAFf0G2XzwaOUxrQ6XNReN/zlltNahxDBqg6ZE0Cle83UY2+rgrlvVdW8FJloNHb+/BtMpMreYOpznza/6665TAh4ho3sgN6bAoxqlIzrYS0tHkr/qZJLhGpNIHDYRN9PMXcjVYL1DGO6x8oLWPxEtnW0h53aVVSojjXYnAA+v1ITUae5RUXFguwamwAbkDhgVMveneQMBmFnA7YH/nD381b+9kfZclKEGITJz5wDEJioEf4h9ioKQWCLOrvC6qucNZ7b4kNFbl24F+qDCpQPXHhgV8/JBi7xI9OVGsRjRzA/SfOwUanianOzSZO/vlWd+VY=
env:
  global:
  - DOCKER_COMPOSE_VERSION=1.6.2
  - SOLR_HOST=slidewiki.imis.athena-innovation.gr
  - SOLR_CONFIG_PORT=8983
  - SOLR_CORE=swikcore
  - SOLR_PATH=/solr
  - SOLR_PROTOCOL=http
  - DATABASE_URL=localhost
  - DATABASE_PORT=27017
  - secure: N/4XZGAKHtywbeMyjqYYuYUlN0nHkldikEMlgFWgtBPyMShTa0i0Wy7Wrk743NXdpoxJY1IR2Beld2vKYbw+K+v/GSB2tbF9wFXGmo4y8c+SdlUjnJwXAtTeh5dnEF10tiYZJDwicDRu3hJboXoL1hufqbaLylqg9qXXYGUmdXA3o2612p+ZIuIWmFkdO1IM1B+1Bo5ylMMCnJFBbWuqktvzghrdMxHBdwnAO34GvAHp3SXN16Q/U1b63JU8wf9zlYm5XerFykQ25jPwii0wthrtPScmkq1jHJjWVLiwyeqAcp8+fUpNOPCxNLRpQSMk9Dvo14RyUt4DgUzYA3H8sp7oXdUf/eMFa5rSGNLCgVw38FoCRRjh9STnKG/myA79chlXKhsK3TGc08pqPo3NVRBeUWcvit4FK0+udkg/CFOgnDMTRcyEkJyPGkWXes97Iw/JTsIy51ZGBnbOJSDHSFzQTESfOQn13b/VxTZ+jz78lsjXNF97mUS+7PXwLCENuTdcCjuGfc0uMSG1YiDG+ORVSYP/RQ6tO70ywm/P7OpweGNlo8Gik57fB1c46MJlVUi7tu7GyDFTDQqnF4eIjOHhpe+sP80iGjuH4NEsDjbNlhS4h1azdqMKQYn3+8dQKEdiciVNOKHHpOBlahelB2ZN40ZX4Co0uen30U63dzE=
  - secure: tWRuVnFRJdPsBjrgyBsT7UOpe0ggdX9VZ0v4ksd7y4hu+ilPB/huDbvq78S3ZmMVFaJi1ZPlVXW9JY7Q0jQ5ESJ4tcMkbKxX0Sdi7f10jeE3hpiF/FDQBEJbQp6nn3c0kQD2JuFQ2xtDr8Dzz4ueVMbpZscYgpaSYHUsRNymuNSfF+ZtAPk10Vzf+vfvKusdnnPr1H265fetQ2BV/NzpBlyRelDbr1FpChUiB/AXcMTwDOmxw/fELWU0+9Z2JsNf38cBQV62LKABg/F4bbkx0UYLdC32iU++eohhvhEsLgTvdsS4tTG2cwSCh83n0bAc9RlqPFOv0JypaTvKlDynMA71fZPU5U5K3H/HnkapJiqCh+D5WvQI8sltA5T5SD9uer+M+7VK97+84dyF46sEX/hRda5BLsfZOJcD0BPIeQWTnuoho4fvmX8skjiMz/+tDI0rwKwKWojQgYaw5fNqfqlRIWK005Wx/gn3pjjuEK9KWkmQoaVhpm6EHrV1GsjpvUBKzujpt4Hd5pbillYLcHZtIKDGLAOHA+mcmFrUHG8M94wyxjticIyX5WUKWki4rZBxpZO1DVoeZpyB2L6ij5SoCKrwXW1zQPyp9+YGBUSC0oez1ciXEPoDRUCGJJYsB0eT9s2KZV6MEfT8DqHUb6FL9CX0WP/JAyJKKf4yJSw=
  - secure: mwlH79GWEHHK692AP9TCuNSdFBlG5dS77vIpAU83o/OC+AVRaNcXQPKdUnCmuw9cmhPljOxDBwvQEE/55Jht5OZGBGC5t9bceJDTKWz2vqdwMrHt7qaALX2OP6CCGSoHGOElbEEEDl60ajJY5WZzX0Vo/QTqpcpIBUyOuRl45P34vc7NEX7IZCNC3cUNZAj5TE60EJhpvxEkoz4cedTHIGKvCEKqDYwfNWnut3mPRMZlTCq9L+xwe5b3UfltIGsUj2zbJ8m2GucYciYzNd98jUlnSwKYz6brDaBxHCqqWXehBPc01bd8xZpGF7017BXLi7f8MvPZLwK0LdZzyqRlskun0mOyQlnQ3wf85cmO+rsRA9hyhDM4MzlPlG0oGbELMVdrHjfVRgyQPybljAA9NvE2YTJ+q6BufsxOkT8j+OZnc/UwWYm9gIJGoGnzeB93s3f9vc4b6nwNmVjnQrDg2pBD50annpmqjOrS4+FTAB99Qbb0NMVY2N/+ecEZIniYrB0r+a7vlwqD6s+19MWOCnvsmWy3P+tovWyeLEhCE0IXmcj6/Flb1dLLUFzRBpAn7sOSM0srsbxzlfAbCqRrZzVbUiKe1EI4zD2TmVZ0cw9DpYU5694MKgS82HUsBZHTNzHiwXN7GmYbjpN1b7dEER8XHJIp7LhjK4lz/557d4E=
  - secure: j1XdKxqb3ARhoXhFiVJFpuEPMu6VC1JASys7i19crjdN3UY43qt+XzPGKzKfLVv8aF3+5fy/6VWr9F0wLaI/z6oB/8fRRey1sLvpNd9YDpI/vVOBdJ87bKFPNccH9EzeQOnQrO5acVriGBhUYcHwOZlwkusJmV1oCxXr5SSkfDzMkaEUGUBlDyx8e/MDV8Z6K5Y6yR4M+NwtgYahlCWh6Aez9eBjYhFxIykbgOplfWPnUK31uZIFZp6brb261n2us+ld4JW7AEwjo3713PqyA9wOqhUCmicghTYgi/ni+XQoIAxekBWfoDl485zFPO11K4j8kZ5kWcwgFdjUl0WOOg+eRsmg1KgTplCw2qWHdS6M+JbWICCDrKEjKPAEsyuoUiZMkuxPnnPVGLm4bzgBxKLFeMSHVinZy4loKL+7guKlMqjrc3Ez2Nqk3H1B474LLw8hvBR3DfPHO458n/rn1Z7X+vmxe/M1daKlGVB8Q5CuudbEun+Wiczy5aRq1EMQdvXaJ3IrGqX7jI+fwwtqocronPkS90rZc72jmU5IAsXQjgyBmuKYRvUThW3ZJXvA5uTUj1Zcjjua2jzTQH9cjK1JKPyoYzXf4TmqND2459DoAzS27OLI6zZghGbRtOB3RyjqObb8F9obsB/wm5wdvhbbV88dc56iF6VDJgvX9cY=
