template:
  image: slidewiki/searchservice
  restart: on-failure:5
  expose:
    - "80"
  external_links:
    - mongodb
    - solr
  environment:
    - APPLICATION_PORT=80
    - DATABASE_PORT=27017
    - VIRTUAL_HOST=searchservice.experimental.slidewiki.org
    - LETSENCRYPT_HOST=searchservice.experimental.slidewiki.org
    - LETSENCRYPT_EMAIL=meissner@informatik.uni-leipzig.de
    - SERVICE_URL_USER=http://userservice.experimental.slidewiki.org
    - SOLR_CORE=swikcore
    - SERVICE_URL_DECK=http://deckservice.experimental.slidewiki.org
    - DATABASE_URL=mongodb # use a url or the name, defined in the docker-compose file
