version: '2'

services:

  web:
    image: slidewiki/searchservice:latest-dev
    restart: on-failure:5
    expose:
      - 80
    external_links:
      - mongodb
      - solr
    environment:
      - APPLICATION_PORT=80
      - VIRTUAL_HOST=searchservice.experimental.slidewiki.org
      - LETSENCRYPT_HOST=searchservice.experimental.slidewiki.org
      - LETSENCRYPT_EMAIL=meissner@informatik.uni-leipzig.de
      - DATABASE_URL=mongodb
      - DATABASE_PORT=27017
      - SOLR_CORE=swikcore
      - SKILLS_CORE=swikskills
      - AGENDA_JOBS_COLLECTION=agendaJobs
      - AGENDA_JOBS_CONCURRENCY=2
    network_mode: bridge

  indexer:
    image: slidewiki/searchservice:latest-dev
    command: 'node worker'
    restart: on-failure:5
    external_links:
      - mongodb
      - solr
    environment:
      - DATABASE_URL=mongodb
      - DATABASE_PORT=27017
      - SERVICE_URL_DECK=http://deckservice.experimental.slidewiki.org
      - SOLR_CORE=swikcore
      - SKILLS_CORE=swikskills
      - AGENDA_JOBS_COLLECTION=agendaJobs
      - AGENDA_JOBS_CONCURRENCY=2
      - JOB_TYPES=searchUpdate
    network_mode: bridge
